from pyspark.sql import SparkSession
from pyspark.sql.functions import col, when, isnan, lit
from pyspark.ml import Pipeline
from pyspark.ml.feature import VectorAssembler, StringIndexer, StandardScaler, Imputer
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# 1. Initialize Spark
spark = SparkSession.builder \
    .appName("IDS_ML_Phase") \
    .config("spark.driver.memory", "4g") \
    .getOrCreate()

spark.sparkContext.setLogLevel("ERROR")

print("--- Phase 3: Ensemble Classification (Fixed for NaN/Infinity) ---")

# 2. Load Pre-Cleaned Data
print("Loading pre-cleaned Parquet data...")
# Read the dataset generated by Preprocessing.scala
df = spark.read.parquet("cleaned_data.parquet").sample(withReplacement=False, fraction=0.1, seed=42)

# Verify no NaNs or Infinities are present (already handed in Scala phase)
print("Data loaded from Scala preprocessing.")

ignore_cols = ["Label", "Timestamp", "Flow ID", "Source IP", "Destination IP"]
feature_cols = [c for c in df.columns if c not in ignore_cols]

# 4. Handle Labels
label_indexer = StringIndexer(inputCol="Label", outputCol="label_index").setHandleInvalid("skip")

# 5. Build Pipeline
assembler = VectorAssembler(inputCols=feature_cols, outputCol="features_raw", handleInvalid="skip")
scaler = StandardScaler(inputCol="features_raw", outputCol="features", withStd=True, withMean=True)
rf = RandomForestClassifier(labelCol="label_index", featuresCol="features", numTrees=20, maxDepth=10, seed=42)

pipeline = Pipeline(stages=[label_indexer, assembler, scaler, rf])

# 6. Train & Evaluate
print("Splitting Data...")
train_data, test_data = df.randomSplit([0.8, 0.2], seed=42)

print("Training Random Forest (this might take 1-2 mins)...")
model = pipeline.fit(train_data)

print("Evaluating...")
predictions = model.transform(test_data)
evaluator = MulticlassClassificationEvaluator(
    labelCol="label_index", predictionCol="prediction", metricName="f1")

f1_score = evaluator.evaluate(predictions)
print("-" * 30)
print(f"SUCCESS: Model Trained.")
print(f"Weighted F1 Score: {f1_score:.4f}")
print("-" * 30)

print("Sample Predictions:")
predictions.select("Label", "label_index", "prediction").show(5)
